!zone defs

; KERNAL methods
SETLFS = $FFBA
OPEN = $FFC0
SETNAM = $FFBD
READST = $FFB7
CHKOUT = $FFC9
CHROUT = $FFD2
CHKIN = $FFC6
CHRIN = $FFCF
PLOT = $FFF0
GETIN = $FFE4
SETMSG = $FF90
CLOSE = $FFC3
PLOT = $FFF0
SCINIT = $FF81
CLRCHN = $FFCC
RSSTAT = $0297
RDTIM = $FFDE

; rs232 buffer pointers
RS232_INBUF_PTR = $f7
RS232_OUTBUF_PTR = $f9

; Colors
COLOR_WHITE = 5
COLOR_GREEN = 30
COLOR_BLACK = 151
COLOR_LIGHT_BLUE = $9A
REVERSE_VIDEO_ON = $12
REVERSE_VIDEO_OFF = $92

COMMAND_TRAILER_CHAR = 126

ZP_TMP_1 = $02
ZP_TMP_2 = $04
ZP_TMP_3 = $06
ZP_TMP_4 = $08

COMMAND_BUFFER_PTR = $08 ; + $04

KEY_DOWN = $11
KEY_UP = $91